version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: 'time.log'
        mode: 'a'
        maxBytes: 5120
        backupCount: 2
loggers:
    'UserSimulation':
        level: DEBUG
        handlers:
            - file
    'SysKey':
        level: INFO
        handlers:
            - file
    'pkg_check':
        level: ERROR
        handlers:
            - file
    'file_log':
        level: CRITICAL
        handlers:
            - file